### ISSUE TITLE
[Discussion] thread-safe network drivers

### ISSUE THREAD

**Issue by evpopov** [FreeRTOS/FreeRTOS-Plus-TCP#1011]
In my product, I'm using a few custom protocols. Those rely on `ipconfigPROCESS_CUSTOM_ETHERNET_FRAMES`
Every once in a while, my device would stop being able to communicate and I couldn't figure out why. I finally tracked it down to the network driver not being thread safe and my custom protocol tasks calling `netIF->pfOutput()` to send out their custom frames.
For those who may still not follow: Normally, `netIF->pfOutput()` is only called from a single task: the +TCP task. Because of that, the output callback function of the network interface does not need to be thread-safe.... until one starts calling it from other tasks. And then it does have to be thread-safe.

There are a few solutions to the issue:

1. Add a mutex to the MAC write code. The problem I see with this one is that it's normal for this code to come from an SDK or library provided my the MCU vendor. In my case, most of the code comes from ASF library that is now provided by Microchip I believe.... That means we should limit how much we modify this code. Another issue is that if there are multiple MAC modules inside an MCU, we need some kind of "per-peripheral"  struct to keep the mutex in.
2. Add a mutex in NetworkInterface.c That is a little better since at least it doesn't modify the vendor-provided files. There is still the problem of multiple peripherals serviced by the same NetworkInterface.c. With this option, I'm also implying that we take/give the mutex inside the `netIF->pfOutput()` function. As with option 1 above, every network driver under the sun would have to be updated to include the mutex take/give code.
3. Add a mutex in `NetworkInterface_t` and take it before every call to `netIF->pfOutput()` The good part of this solution is that the mutex is stored in what I'd call a very good place. It is within the network interface structure and it protects the hardware for this interface so that makes sense. Another good think about this solution is that the network drivers don't need to be modified individually. The bad part is, I'm finding 9 places where `netIF->pfOutput()` is being called, so that's 9 places where we need to add take/give code.

Please keep in mind that I'm envisioning that any solution to this issue would be inside a `#if ( ipconfigPROCESS_CUSTOM_ETHERNET_FRAMES != 0 )` so that it wouldn't add code for the majority of users.

I personally am gravitating towards keeping the mutex in `NetworkInterface_t` and placing the take/give call in NetworkInterface.c. I say this only because in general I try not to touch the common/core code of +TCP. However option 3 above is quite appealing.
In any case, the documentation for `ipconfigPROCESS_CUSTOM_ETHERNET_FRAMES` should also be updated to instruct users that enable it to also take/give the network interface mutex if they are calling  `netIF->pfOutput()` from their own tasks.

With that being said, I am very interested to hear your opinion about the issue and the proposed solutions. I'm also volunteering to do a PR for this if the developers/maintainers believe it is worth it and once we decide on the best approach.

**Comment by htibosch** [comment]
Hello @evpopov, your task can send a message of type `eNetworkTxEvent`.
In that way, `netIF->pfOutput()` will be called by the IP-task and no mutex will be needed.
Would that work for you?
Probably the message `eNetworkTxEvent` has not been well documented, because people rarely need it. But I think it is exactly what you are looking for.

**Comment by evpopov** [comment]
That's a pretty nice idea @htibosch. I was not aware of this.
Yes, this should solve the issue. I'll give it a try next week and if it resolves the problem I will close this issue.

**Comment by htibosch** [comment]
Here is an example of using `eNetworkTxEvent`:
~~~
IPStackEvent_t xSendEvent;

/* Send a message to the IP-task to send this ARP packet. */
xSendEvent.eEventType = eNetworkTxEvent;
xSendEvent.pvData = pxNetworkBuffer;

if( xSendEventStructToIPTask( &xSendEvent, ( TickType_t ) portMAX_DELAY ) == pdFAIL )
{
	/* Failed to send the message, so release the network buffer. */
	vReleaseNetworkBufferAndDescriptor( pxNetworkBuffer );
}
~~~
Please note that:

- The field `pxInterface` must be set to point to the right interface
- The buffer will be released by the IP-task
- when `xSendEventStructToIPTask` fails, the buffer must be released manually

No mutex:
---

FreeRTOS+TCP does not use mutexes or semaphores as a locking mechanism. That is possible because the IP-task has unique access to all logic.
TCP data is buffered in circular buffers, that do not need access protection as they have a single reader/writer.
The API is simply called by `xSendEventStructToIPTask()`. For some API types, the IP-task will set a flag in the socket's `xEventGroup` to wake it up.

We always like to recommend to use this priority scheme:

- High: network interface
- Normal: the IP-task
- Low: all task that use TCP/IP

In this way, chances are smaller that there is a traffic jam in either the network interface, or in the IP-task.

And one more thing: in +TCP you rarely see critical sections or calls to `vTaskSuspendAll()` in the library. And exception is seen when accessing `xBoundUDPSocketsList`: both the network interface and the IP-task may look up sockets.

Buffer allocation wants to call `taskENTER_CRITICAL()`, because in some projects an ISR will allocate or release a buffer (not my favorite choice).

**Comment by evpopov** [comment]
@htibosch, sorry for the late reply. I was finally able to look into the details and yes, this approach will completely solve my conundrum with my custom protocols. It adds 1 queue processing and an extra function call so it adds a bit of CPU usage, but  so does my thread-safety mutex addition. I agree that the less explicit critical sections and mutexes, the better and cleaner the code is. I think this particular issue is now resolved. Thanks again.
