### ISSUE TITLE
[Feature Request] Standardize Function Naming Conventions

### ISSUE THREAD

**Issue by HTRamsey** [FreeRTOS/FreeRTOS-Plus-TCP#1069]
The function naming conventions should be more universal, such as with capitalization in the case of `FreeRTOS_SignalSocket` vs `FreeRTOS_closesocket`. I would suggest renaming as needed for next major version and include macros to link to the old names.

Also there are some functions such as `xSocketSetSocketID`/`pvSocketGetSocketID` which state are only used by the user but don't have the API naming convention.

**Comment by htibosch** [comment]
@HTRamsey wrote:

> The function naming conventions should be more universal, such as with capitalization in the case of `FreeRTOS_SignalSocket` vs `FreeRTOS_closesocket`.

The function `FreeRTOS_SignalSocket` is using Camel case because there is not a corresponding `signalsocket()`, although the function `signal()` is quite similar: it can interrupt an API.

All BSD functions are in small letters and preceded by `FreeRTOS_`, such as `FreeRTOS_bind()`.
